# NumPy

> Numerical Python is a library for storing large numerical arrays in a efficient way and apply operations on them.

- All items in a numpy array have to be the same type

In [1]:
import numpy as np

## Create Arrays

Integer array:

In [2]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

Using the `dtype` attribute you can set the [type](https://docs.scipy.org/doc/numpy/user/basics.types.html).

In [3]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

or

In [4]:
np.array([1, 2, 3, 4], dtype=np.float32)

array([1., 2., 3., 4.], dtype=float32)

## Multi dimensional Arrays

In [5]:
x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

## Usefull Atributes

In [12]:
print('ndim:', x3.ndim)
print('shape', x3.shape)
print('size', x3.size)

print('itemsize', x3.itemsize)
print('nbytes', x3.nbytes)

print('dtype', x3.dtype)

ndim: 3
shape (3, 4, 5)
size 60
itemsize 8
nbytes 480
dtype int64


## Indexing

`python` starts with 0.

In [16]:
x1

array([0, 2, 0, 7, 9, 7])

In [15]:
x1[0]

0

negative indexes can be used to get a value from the end of the array

In [14]:
# get the last item
x1[-1]

7

In [17]:
x2[0, 0]

0

## Slicing

`x[start:stop:step]`

defaults:
- `start=0`
- `stop size of dimension`
- `step=1`

In [18]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[:5]  # first five elements