# NumPy

> Numerical Python is a library for storing large numerical arrays in a efficient way and apply operations on them.

- All items in a numpy array have to be the same type

In [2]:
import numpy as np

## Create Arrays

Integer array:

In [2]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

Using the `dtype` attribute you can set the [type](https://docs.scipy.org/doc/numpy/user/basics.types.html).

In [3]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

or

In [4]:
np.array([1, 2, 3, 4], dtype=np.float32)

array([1., 2., 3., 4.], dtype=float32)

## Multi dimensional Arrays

In [5]:
x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

## Usefull Atributes

In [12]:
print('ndim:', x3.ndim)
print('shape', x3.shape)
print('size', x3.size)

print('itemsize', x3.itemsize)
print('nbytes', x3.nbytes)

print('dtype', x3.dtype)

ndim: 3
shape (3, 4, 5)
size 60
itemsize 8
nbytes 480
dtype int64


## Indexing

`python` starts with 0.

In [16]:
x1

array([0, 2, 0, 7, 9, 7])

In [15]:
x1[0]

0

negative indexes can be used to get a value from the end of the array

In [14]:
# get the last item
x1[-1]

7

In [17]:
x2[0, 0]

0

## Slicing

`x[start:stop:step]`

defaults:
- `start=0`
- `stop size of dimension`
- `step=1`

In [18]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
x[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [20]:
x[5:]  # elements after index 5

array([5, 6, 7, 8, 9])

In [21]:
x[3:4]

array([3])

In [22]:
x[::2]

array([0, 2, 4, 6, 8])

In [24]:
x[::-1] #reversed array

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [25]:
x2

array([[0, 3, 2, 1],
       [7, 0, 4, 2],
       [8, 5, 7, 7]])

In [26]:
x2[:2, :3]  # two rows, three columns

array([[0, 3, 2],
       [7, 0, 4]])

In [27]:
x2[:, 0]  #first column of x2

array([0, 7, 8])

In [28]:
x2[0] #first row of x2

array([0, 3, 2, 1])

## Reshaping

In [30]:
x = np.array([1, 2, 3, 4, 5, 6])

# row vector via reshape
x.reshape((2, 3))

array([[1, 2, 3],
       [4, 5, 6]])

## Concatenation

In [31]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [33]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

## Splitting

In [35]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


## Array Arithmetics

In [4]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # floor division
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


## Aggregations

### Python Functions

In [3]:
L = np.random.random(100)
print('sum', sum(L))
print('max', max(L))
print('min', min(L))

sum 51.340258050338086
max 0.9947491447124661
min 0.007939943322706755


But those functions are much slower than the `NumPy` equivalents

### NumPy Functions

In [4]:
print('sum', np.sum(L))
print('max', np.max(L))
print('min', np.min(L))

sum 51.340258050338065
max 0.9947491447124661
min 0.007939943322706755


These functions can also be called directly on the array itself.

In [5]:
print('sum', L.sum())
print('max', L.max())
print('min', L.min())

sum 51.340258050338065
max 0.9947491447124661
min 0.007939943322706755


In [6]:
M = np.random.random((3, 4))
M

array([[0.38217525, 0.4688325 , 0.20803177, 0.90834701],
       [0.45085714, 0.76623193, 0.08959703, 0.74853466],
       [0.75950913, 0.73191253, 0.6604043 , 0.53867557]])

In [7]:
M.sum()

6.713108807342031

In [8]:
M.sum(axis=0)

array([1.59254151, 1.96697695, 0.95803311, 2.19555724])

In [9]:
M.sum(axis=1)

array([1.96738653, 2.05522076, 2.69050152])

## Comparison

In [12]:
x = np.array([1, 2, 3, 4, 5])
x < 3

array([ True,  True, False, False, False])

Sign | Meaning
--- | ---
`==` | equals
`<` | smaller than
`<=` | smaller or equal
`>` | bigger
`>=` | bigger or equal
`!=` | unequal
`&` | logical and
`\|` | logical or
`~` | logical not

In [13]:
np.sum(x < 3)

2

In [14]:
np.any(x > 4)

True

In [15]:
np.all(x == 3)

False

In [17]:
np.sum((x < 4) & (x > 2))

1

## Selecting Values

In [18]:
x[x < 3]

array([1, 2])

### Fancy Indexing

In [19]:
ind = [1, 2, 4]
x[ind]

array([2, 3, 5])

In [20]:
x = np.arange(10)
i = np.array([2, 1, 8, 4])
x[i] = 99
x

array([ 0, 99, 99,  3, 99,  5,  6,  7, 99,  9])

## Sorting

In [21]:
x = np.array([2, 1, 4, 3, 5])
np.sort(x)

array([1, 2, 3, 4, 5])